export interface MagicWandField {
  key: string;
  label: string;
}

export interface MagicWandCategory {
  slug: string;
  title: string;
  emoji: string;
  fields: MagicWandField[];
}

export const categories: MagicWandCategory[] = [
  {
    slug: 'wealth',
    title: 'Wealth & Finances',
    emoji: '💰',
    fields: [
      { key: 'net_worth', label: 'Net worth' },
      { key: 'liquid_cash', label: 'Liquid cash position' },
      { key: 'revenue_streams', label: 'Revenue streams (list them)' },
      { key: 'passive_active_ratio', label: 'Passive vs active income ratio' },
      { key: 'investment_portfolio', label: 'Investment portfolio' },
      { key: 'debt_situation', label: 'Debt situation' },
      { key: 'freedom_number', label: 'Financial runway / freedom number' },
      { key: 'lifestyle_budget', label: 'Monthly lifestyle budget' },
      { key: 'money_feeling', label: 'Relationship with money (how does it feel?)' },
    ],
  },
  {
    slug: 'career',
    title: 'Career & Business',
    emoji: '🏗️',
    fields: [
      { key: 'primary_role', label: 'Role at Yellow — what does it look like' },
      { key: 'ventures_equity', label: 'Own ventures / equity positions' },
      { key: 'reputation', label: 'Industry reputation & thought leadership' },
      { key: 'speaking', label: 'Conference speaking / stage presence' },
      { key: 'team', label: 'Team built around you' },
      { key: 'traction', label: 'Revenue / traction of projects' },
      { key: 'investors', label: 'Relationship with investors / board' },
      { key: 'launches_exits', label: 'New launches or exits' },
      { key: 'work_feeling', label: 'How does work FEEL day to day' },
    ],
  },
  {
    slug: 'music',
    title: 'Music & Creative (ZYLER)',
    emoji: '🎵',
    fields: [
      { key: 'brand_status', label: 'Brand status — where is ZYLER in a year' },
      { key: 'release_cadence', label: 'Release cadence (tracks, EPs, collabs)' },
      { key: 'gigs', label: 'Gig schedule / residencies' },
      { key: 'festivals', label: 'Festival bookings' },
      { key: 'fan_base', label: 'Fan base size & engagement' },
      { key: 'studio', label: 'Studio setup & production quality' },
      { key: 'collaborations', label: 'Collaborations' },
      { key: 'music_income', label: 'Music income vs hobby balance' },
      { key: 'music_feeling', label: 'How does making music FEEL' },
    ],
  },
  {
    slug: 'living',
    title: 'Living Situation',
    emoji: '🏠',
    fields: [
      { key: 'primary_base', label: 'Primary home base' },
      { key: 'secondary_bases', label: 'Secondary bases' },
      { key: 'space_quality', label: 'Quality of space — size, vibe, design' },
      { key: 'neighborhood', label: 'Neighborhood / community' },
      { key: 'home_studio', label: 'Home studio setup' },
      { key: 'aesthetics', label: 'Aesthetics — furniture, art, feel' },
      { key: 'tech_setup', label: 'Smart home / tech setup' },
      { key: 'home_feeling', label: 'How does coming home FEEL' },
    ],
  },
  {
    slug: 'travel',
    title: 'Travel & Lifestyle',
    emoji: '🌍',
    fields: [
      { key: 'cities', label: 'Cities in rotation' },
      { key: 'travel_style', label: 'Travel frequency & style' },
      { key: 'favorite_destinations', label: 'Favorite destinations locked in' },
      { key: 'travel_companions', label: 'Travel companions' },
      { key: 'remote_infra', label: 'Work-from-anywhere infrastructure' },
      { key: 'bucket_list', label: 'Bucket list trips completed this year' },
      { key: 'travel_feeling', label: 'How does travel FEEL vs now' },
    ],
  },
  {
    slug: 'health',
    title: 'Health & Body',
    emoji: '💪',
    fields: [
      { key: 'fitness_level', label: 'Physical fitness level / body composition' },
      { key: 'workout_routine', label: 'Workout routine & consistency' },
      { key: 'diet', label: 'Diet & nutrition approach' },
      { key: 'sleep', label: 'Sleep quality & hours' },
      { key: 'energy', label: 'Daily energy levels' },
      { key: 'health_resolved', label: 'Health issues resolved' },
      { key: 'biohacking', label: 'Biohacking / longevity practices' },
      { key: 'substances', label: 'Relationship with substances / alcohol' },
      { key: 'body_feeling', label: 'How does your body FEEL' },
    ],
  },
  {
    slug: 'mental',
    title: 'Mental & Emotional',
    emoji: '🧠',
    fields: [
      { key: 'stress', label: 'Stress levels' },
      { key: 'clarity', label: 'Mental clarity & focus' },
      { key: 'mindfulness', label: 'Meditation / mindfulness practice' },
      { key: 'therapy', label: 'Therapy / coaching' },
      { key: 'resilience', label: 'Emotional resilience' },
      { key: 'peace_hustle', label: 'Inner peace vs hustle balance' },
      { key: 'confidence', label: 'Confidence & self-image' },
      { key: 'uncertainty', label: 'Relationship with uncertainty' },
      { key: 'mind_feeling', label: 'How does your mind FEEL most days' },
    ],
  },
  {
    slug: 'love',
    title: 'Relationships & Love',
    emoji: '❤️',
    fields: [
      { key: 'romantic_status', label: 'Romantic relationship status' },
      { key: 'relationship_quality', label: 'Quality of that relationship' },
      { key: 'as_partner', label: 'How you show up as a partner' },
      { key: 'boundaries', label: 'Boundaries & communication' },
      { key: 'love_feeling', label: 'What does love FEEL like' },
    ],
  },
  {
    slug: 'social',
    title: 'Social & Community',
    emoji: '👥',
    fields: [
      { key: 'inner_circle', label: 'Inner circle — your 5 closest people' },
      { key: 'friendship_quality', label: 'Quality of friendships' },
      { key: 'social_life', label: 'Social life frequency & satisfaction' },
      { key: 'communities', label: 'Communities you belong to' },
      { key: 'mentors', label: 'Mentors in your life' },
      { key: 'mentees', label: 'People you mentor' },
      { key: 'networking', label: 'Networking depth vs breadth' },
      { key: 'solitude', label: 'Loneliness vs solitude balance' },
    ],
  },
  {
    slug: 'family',
    title: 'Family',
    emoji: '👨‍👩‍👧',
    fields: [
      { key: 'family_relationships', label: 'Relationship with parents / siblings' },
      { key: 'obligations', label: 'Family obligations & boundaries' },
      { key: 'future_family', label: 'Future family plans' },
      { key: 'family_frequency', label: 'How often you see family' },
      { key: 'family_feeling', label: 'How does family FEEL' },
    ],
  },
  {
    slug: 'learning',
    title: 'Learning & Growth',
    emoji: '📚',
    fields: [
      { key: 'skills_developed', label: 'Skills developed this year' },
      { key: 'books_courses', label: 'Books / courses completed' },
      { key: 'languages', label: 'Languages learned or improved' },
      { key: 'expertise', label: 'Areas of expertise deepened' },
      { key: 'curiosity', label: 'Intellectual curiosity — is it fed' },
      { key: 'biggest_lesson', label: 'Biggest lesson learned this year' },
    ],
  },
  {
    slug: 'purpose',
    title: 'Purpose & Legacy',
    emoji: '🎯',
    fields: [
      { key: 'known_for', label: 'What are you known for' },
      { key: 'impact', label: 'Impact you\'re making' },
      { key: 'alignment', label: 'Alignment — daily work vs deeper mission' },
      { key: 'legacy', label: 'Legacy you\'re building' },
      { key: 'causes', label: 'Causes you support' },
      { key: 'meaning_score', label: 'Feeling of meaning (1-10)' },
    ],
  },
  {
    slug: 'daily',
    title: 'Daily Experience',
    emoji: '⚡',
    fields: [
      { key: 'typical_monday', label: 'Typical Monday looks like' },
      { key: 'typical_saturday', label: 'Typical Saturday looks like' },
      { key: 'morning_routine', label: 'Morning routine' },
      { key: 'evening_routine', label: 'Evening routine' },
      { key: 'time_ratio', label: 'Ratio — meetings vs deep work vs play' },
      { key: 'screen_time', label: 'Screen time habits' },
      { key: 'flow_frequency', label: 'How often you feel "in flow"' },
      { key: 'wake_up_feeling', label: 'What\'s the first thing you feel when you wake up' },
    ],
  },
  {
    slug: 'fun',
    title: 'Fun & Recreation',
    emoji: '🎨',
    fields: [
      { key: 'hobbies', label: 'Hobbies outside music & work' },
      { key: 'adventures', label: 'Adventures & experiences this year' },
      { key: 'nightlife', label: 'Nightlife & social scenes' },
      { key: 'sports', label: 'Sports or physical activities for fun' },
      { key: 'creative_outlets', label: 'Creative outlets beyond music' },
      { key: 'vacation_ratio', label: 'Vacations vs workcations ratio' },
    ],
  },
  {
    slug: 'systems',
    title: 'Systems & Infrastructure',
    emoji: '🔧',
    fields: [
      { key: 'assistant_team', label: 'Personal assistant / team support' },
      { key: 'ai_tools', label: 'AI tools & automation in your life' },
      { key: 'legal_tax', label: 'Legal / tax structure' },
      { key: 'insurance', label: 'Insurance & protection' },
      { key: 'digital_org', label: 'Digital organization' },
      { key: 'content_system', label: 'Content creation system' },
    ],
  },
  {
    slug: 'presence',
    title: 'Digital & Online Presence',
    emoji: '📱',
    fields: [
      { key: 'x_following', label: 'X following & engagement' },
      { key: 'linkedin', label: 'LinkedIn positioning' },
      { key: 'personal_brand', label: 'Personal brand clarity' },
      { key: 'content_strategy', label: 'Content strategy' },
      { key: 'reputation', label: 'Online reputation' },
      { key: 'privacy_visibility', label: 'Privacy vs visibility balance' },
    ],
  },
  {
    slug: 'spirituality',
    title: 'Spirituality & Inner Life',
    emoji: '🙏',
    fields: [
      { key: 'spiritual_practice', label: 'Spiritual practice' },
      { key: 'gratitude', label: 'Gratitude practice' },
      { key: 'bigger_connection', label: 'Connection to something bigger' },
      { key: 'top_values', label: 'Values clarity — top 5 values' },
      { key: 'integrity', label: 'Integrity alignment — living what you believe' },
    ],
  },
  {
    slug: 'big_picture',
    title: 'The Big Picture',
    emoji: '🔥',
    fields: [
      { key: 'top3_light_up', label: 'Top 3 areas that light you up the most' },
      { key: 'top3_gap', label: 'Top 3 areas with the biggest gap from today' },
      { key: 'one_thing', label: 'The ONE thing that would change everything' },
      { key: 'surprise', label: 'What surprised you about your answers' },
      { key: 'most_excited', label: 'What are you most excited about' },
      { key: 'most_scared', label: 'What are you most scared of' },
    ],
  },
];
